# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "* 23 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Remove hosts
      run: rm ./hosts.txt
      
    - name: Remove whiteslist
      run: rm ./whitelist.txt      
      
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
           commit_message: Remove Old Files
           commit_options: '--no-verify --signoff'
           repository: .
           commit_user_name: FusionPlmH
           commit_user_email: leemenhin@gmail.com
    

    
        # Runs a single command using the runners shell
    - name: Run a one-line script
      run: bash ./host.sh
      
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
           commit_message: Apply automatic changes
           commit_options: '--no-verify --signoff'
           repository: .
           commit_user_name: FusionPlmH
           commit_user_email: leemenhin@gmail.com
    
    
